homeassistant:
  # Name of the location where Home Assistant is running
  name: Orchard House
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 94
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization files
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  # Packages
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# https://github.com/custom-components/custom_updater
custom_updater:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
# discovery:

# System Health
system_health:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# MQTT
mqtt:
  broker: MQTT
  port: 1883
  client_id: homeassistant
  birth_message:
    topic: 'orchardhouse/homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'orchardhouse/homeassistant/status'
    payload: 'offline'

# Recorder
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 2
  purge_interval: 1

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Use InfluxDB
influxdb: 
  host: influxdb
  include:
    domains:
      - sensor
  exclude:
    entities:
      - sensor.btb_gate_closed
  tags:
    source: ha

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
# tts:
#   - platform: google_translate

# Cloud
cloud:

tado:
  username:     !secret tado_username
  password:     !secret tado_password

person:
  - name: Brad
    id: brad
    device_trackers:
      - device_tracker.brad
      - device_tracker.life360_brad
  - name: Heather
    id: heather
    device_trackers:
      -  device_tracker.heather

sensor:         !include sensors.yaml
binary_sensor:  !include binary_sensors.yaml
#light:          !include lights.yaml
#switch:         !include switches.yaml  
device_tracker: !include device_tracker.yaml  

#group:          !include groups.yaml
#automation:     !include automations.yaml
#script:         !include scripts.yaml
zone:           !include zones.yaml