binary_sensor:
  - platform: "mqtt"
    name: back_gate_motion_occupancy
    state_topic: "zigbee2mqtt/back_gate_motion/occupancy"
    availability_topic: "zigbee2mqtt/back_gate_motion/availability"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: back_gate_motion_illuminance
    state_topic: "zigbee2mqtt/back_gate_motion/illuminance"
    availability_topic: "zigbee2mqtt/back_gate_motion/availability"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: back_gate_motion_temperature
    state_topic: "zigbee2mqtt/back_gate_motion/temperature"
    availability_topic: "zigbee2mqtt/back_gate_motion/availability"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: back_gate_motion_battery
    state_topic: "zigbee2mqtt/back_gate_motion/battery"
    availability_topic: "zigbee2mqtt/back_gate_motion/availability"
    unit_of_measurement: "%"
    device_class: "battery"

light:
  - platform: "mqtt"
    name: driveway_corner_light
    schema: "template"
    command_topic: "shellies/driveway-corner-light/light/0/set"
    command_off_template: >
      {
        "brightness": 0,
        "turn": "off"
      }
    command_on_template: >
      {
        "brightness": {{ ((brightness or 255) / 255 * 100) | round(0, 'ceil') | int }},
        "turn": "on"
      }
    state_topic: "shellies/driveway-corner-light/light/0/status"
    state_template: "{{ 'on' if value_json.ison else 'off' }}"
    brightness_template: "{{ (value_json.brightness * 255 / 100) | int }}"
    retain: true
    availability_topic: "shellies/driveway-corner-light/online"
    payload_available: "true"
    payload_not_available: "false"
    
  - platform: "mqtt"
    name: back_garden_wall_light_1
    schema: "template"
    command_topic: "shellies/back-garden-wall-light-1/light/0/set"
    command_off_template: >
      {
        "brightness": 0,
        "turn": "off"
      }
    command_on_template: >
      {
        "brightness": {{ ((brightness or 255) / 255 * 100) | round(0, 'ceil') | int }},
        "turn": "on"
      }
    state_topic: "shellies/back-garden-wall-light-1/light/0/status"
    state_template: "{{ 'on' if value_json.ison else 'off' }}"
    brightness_template: "{{ (value_json.brightness * 255 / 100) | int }}"
    retain: true
    availability_topic: "shellies/back-garden-wall-light-1/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: "mqtt"
    name: back_garden_wall_light_2
    schema: "template"
    command_topic: "shellies/back-garden-wall-light-2/light/0/set"
    command_off_template: >
      {
        "brightness": 0,
        "turn": "off"
      }
    command_on_template: >
      {
        "brightness": {{ ((brightness or 255) / 255 * 100) | round(0, 'ceil') | int }},
        "turn": "on"
      }
    state_topic: "shellies/back-garden-wall-light-2/light/0/status"
    state_template: "{{ 'on' if value_json.ison else 'off' }}"
    brightness_template: "{{ (value_json.brightness * 255 / 100) | int }}"
    retain: true
    availability_topic: "shellies/back-garden-wall-light-2/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: "group"
    name: back_garden_wall_lights
    entities:
      - light.back_garden_wall_light_1
      - light.back_garden_wall_light_2