binary_sensor:
  - platform: "mqtt"
    name: back_garden_motion_1_occupancy
    state_topic: "zigbee2mqtt/back_garden_motion_1/occupancy"
    availability_topic: "zigbee2mqtt/back_garden_motion_1/availability"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: back_garden_motion_1_illuminance
    state_topic: "zigbee2mqtt/back_garden_motion_1/illuminance"
    availability_topic: "zigbee2mqtt/back_garden_motion_1/availability"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: back_garden_motion_1_temperature
    state_topic: "zigbee2mqtt/back_garden_motion_1/temperature"
    availability_topic: "zigbee2mqtt/back_garden_motion_1/availability"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: back_garden_motion_1_battery
    state_topic: "zigbee2mqtt/back_garden_motion_1/battery"
    availability_topic: "zigbee2mqtt/back_garden_motion_1/availability"
    unit_of_measurement: "%"
    device_class: "battery"