switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/electric_blanket_heather"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/electric_blanket_heather/set"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/electric_blanket_brad"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/electric_blanket_brad/set"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/electric_blanket_heather"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/electric_blanket_brad"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:signal"
    unit_of_measurement: "lqi"
    value_template: "{{ value_json.linkquality }}"