###############
# Brad Mobile #
###############

binary_sensor:
  - platform: mqtt
    name: brad_mobile_seat_leon
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.SeatLeon }}"
    payload_on: true
    payload_off: false
    
  - platform: bayesian
    name: 'brad_in_office'
    prior: 0.2678571428571
    observations:
    - entity_id: 'binary_sensor.brad_mobile_seat_leon'
      prob_given_true: 0.01
      prob_given_false: 0.2848101265822
      platform: 'state'
      to_state: 'on'
    - entity_id: 'device_tracker.life360_brad'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'Enable'
    - entity_id: 'sensor.brad_mobile_ssid'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'Enable Guest Wifi'
    - entity_id: 'sensor.brad_mobile_ssid'
      prob_given_true: 0.001
      prob_given_false: 0.4787
      platform: 'state'
      to_state: 'Orchard House'

sensor:
  - platform: mqtt
    name: brad_mobile_ssid
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.SSID }}"

  - platform: mqtt
    name: brad_mobile_volume_ringer
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.VolumeRinger }}"
  
  - platform: mqtt
    name: brad_mobile_volume_media
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.VolumeMedia }}"

  - platform: mqtt
    name: brad_mobile_volume_alarm
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.VolumeAlarm }}"

  - platform: mqtt
    name: brad_mobile_volume_notification
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.VolumeNotification }}"

  - platform: mqtt
    name: brad_mobile_volume_system
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.VolumeSystem }}"

  - platform: mqtt
    name: brad_mobile_silent_mode
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.SilentMode }}"

  - platform: mqtt
    name: brad_mobile_battery_level
    state_topic: "orchardhouse/brad20pro/status"
    value_template: "{{ value_json.BatteryLevel }}"

input_number:
  enable_current_password_integer:
    min: 0
    max: 99999
    step: 1
    mode: box
    icon: mdi:textbox-password

switch:
  - platform: rest
    name: 'enable_status'
    resource: http://node-red:1880/api/enable/status
    method: PUT
    timeout: 120 # 2 minutes
    body_on: 1
    body_off: 0
    scan_interval: 1800 # 30 minutes
    headers:
      Content-Type: text/plain