light:
  - platform: mqtt
    name: cloakroom
    command_topic: "shellies/cloakroom-light/relay/0/command"
    state_topic: "shellies/cloakroom-light/relay/0"
    payload_on: "on"
    payload_off: "off"
    retain: true
    availability_topic: "shellies/cloakroom-light/online"
    payload_available: "true"
    payload_not_available: "false"

binary_sensor:
  - platform: mqtt
    name: cloakroom_light_switch
    state_topic: "shellies/cloakroom-light/input/0"
    payload_on: "1"
    payload_off: "0"
    availability_topic: "shellies/cloakroom-light/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: "mqtt"
    name: cloakroom_motion_occupancy
    state_topic: "zigbee2mqtt/cloakroom_motion/occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: cloakroom_motion_illuminance
    state_topic: "zigbee2mqtt/cloakroom_motion/illuminance"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: cloakroom_motion_battery
    state_topic: "zigbee2mqtt/cloakroom_motion/battery"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"