climate:
  - platform: mqtt
    name: Dehumidifier
    action_topic: "tuya/dehumidifier/mode"
    mode_state_topic: "tuya/dehumidifier/mode"
    mode_command_topic: "tuya/dehumidifier/mode/set"
    modes:
      - "auto"
      - "heat"
      - "dry"
      - "fan_only"
    power_command_topic: "tuya/dehumidifier/power/set"
    payload_on: "true"
    payload_off: "false"
    current_temperature_topic: "tuya/dehumidifier/temperature"
    temperature_command_topic: "tuya/dehumidifier/temperature_target/set"
    temperature_state_topic: "tuya/dehumidifier/temperature_target"
    fan_mode_command_topic: "tuya/dehumidifier/fan/set"
    fan_mode_state_topic: "tuya/dehumidifier/fan"
    fan_modes:
      - "low"
      - "medium"
      - "high"
    max_temp: 30.0
    min_temp: 15.0
    precision: 1.0

switch:
  - platform: mqtt
    name: Dehumidifier ioniser
    command_topic: "tuya/dehumidifier/ioniser/set"
    payload_off: "false"
    payload_on: "true"
    state_topic: "tuya/dehumidifier/ioniser"
    state_off: "false"
    state_on: "true"
    availability_topic: "tuya/dehumidifier/power"
    payload_available: "true"
    payload_not_available: "false"

  - platform: mqtt
    name: Dehumidifier UV
    command_topic: "tuya/dehumidifier/uv/set"
    payload_off: "false"
    payload_on: "true"
    state_topic: "tuya/dehumidifier/uv"
    state_off: "false"
    state_on: "true"
    availability_topic: "tuya/dehumidifier/power"
    payload_available: "true"
    payload_not_available: "false"

sensor:
  - platform: mqtt
    name: Dehumidifier current humidity
    device_class: humidity
    state_topic: "tuya/dehumidifier/humidity"
    unit_of_measurement: "%"
    availability_topic: "tuya/dehumidifier/power"
    payload_available: "true"
    payload_not_available: "false"

input_number:
  dehumidifier_target_humidity:
    min: 35
    max: 90
    step: 1
    mode: box
    icon: mdi:water-percent
    unit_of_measurement: "%"

automation:
  - alias: Dehumdifier - target humdity mqtt
    trigger:
      platform: mqtt
      topic:  "tuya/dehumidifier/humidity_target"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.dehumidifier_target_humidity
        value: "{{ trigger.payload }}"

  - alias: Dehumidifier - target humidity set
    trigger:
      platform: state
      entity_id: input_number.dehumidifier_target_humidity
    action:
      service: mqtt.publish
      data_template:
        topic: "tuya/dehumidifier/humidity_target/set"
        payload: "{{ states('input_number.dehumidifier_target_humidity') | int }}"