light:
  - platform: mqtt
    name: garage
    command_topic: "shellies/garage-light/relay/0/command"
    state_topic: "shellies/garage-light/relay/0"
    payload_on: "on"
    payload_off: "off"
    retain: true
    availability_topic: "shellies/garage-light/online"
    payload_available: "true"
    payload_not_available: "false"

binary_sensor:
  - platform: mqtt
    name: garage_light_switch
    state_topic: "shellies/garage-light/input/0"
    payload_on: "1"
    payload_off: "0"
    availability_topic: "shellies/garage-light/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: mqtt
    name: garage_side_door
    state_topic: "shellies/garage-side-door/sensor/state"
    payload_on: "open"
    payload_off: "close"
    device_class: "door"

sensor:
  - platform: mqtt
    name: garage_side_door_battery
    state_topic: "shellies/garage-side-door/sensor/battery"
    unit_of_measurement: "%"
    device_class: "battery"