binary_sensor:
  - platform: "mqtt"
    name: hall_motion_1
    state_topic: "zigbee2mqtt/hall_motion_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    off_delay: 1
    value_template: "{{ value_json.occupancy }}"
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: hall_motion_1_illuminance
    state_topic: "zigbee2mqtt/hall_motion_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"
    value_template: "{{ value_json.illuminance }}"

  - platform: "mqtt"
    name: hall_motion_1_battery
    state_topic: "zigbee2mqtt/hall_motion_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

  - platform: "mqtt"
    name: hall_motion_1_linkquality
    state_topic: "zigbee2mqtt/hall_motion_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"