light:
  - platform: mqtt
    name: hall
    command_topic: "shellies/hall-light/relay/0/command"
    state_topic: "shellies/hall-light/relay/0"
    payload_on: "on"
    payload_off: "off"
    retain: true
    availability_topic: "shellies/hall-light/online"
    payload_available: "true"
    payload_not_available: "false"

binary_sensor:
  - platform: mqtt
    name: hall_light_switch
    state_topic: "shellies/hall-light/input/0"
    payload_on: "1"
    payload_off: "0"
    availability_topic: "shellies/hall-light/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: "mqtt"
    name: hall_motion_1_occupancy
    state_topic: "zigbee2mqtt/hall_motion_1/occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

  - platform: "mqtt"
    name: hall_motion_2_occupancy
    state_topic: "zigbee2mqtt/hall_motion_2/occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

  - platform: "mqtt"
    name: hall_motion_3_occupancy
    state_topic: "zigbee2mqtt/hall_motion_3/occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: hall_motion_1_illuminance
    state_topic: "zigbee2mqtt/hall_motion_1/illuminance"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: hall_motion_1_battery
    state_topic: "zigbee2mqtt/hall_motion_1/battery"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"

  - platform: "mqtt"
    name: hall_motion_2_illuminance
    state_topic: "zigbee2mqtt/hall_motion_2/illuminance"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: hall_motion_2_battery
    state_topic: "zigbee2mqtt/hall_motion_2/battery"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"

  - platform: "mqtt"
    name: hall_motion_3_illuminance
    state_topic: "zigbee2mqtt/hall_motion_3/illuminance"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: hall_motion_1_battery
    state_topic: "zigbee2mqtt/hall_motion_3/battery"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"