light:
  - platform: "mqtt"
    name: kitchen_ceiling_group
    state_topic: "zigbee2mqtt/kitchen_ceiling_group" # zigbee2mqtt group friendlyname: kitchen_ceiling_group
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    schema: "json"
    command_topic: "zigbee2mqtt/kitchen_ceiling_group/set"

  - platform: "mqtt"
    name: kitchen_ceiling_1
    state_topic: "zigbee2mqtt/kitchen_ceiling_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    schema: "json"
    command_topic: "zigbee2mqtt/kitchen_ceiling_1/set"

  - platform: "mqtt"
    name: kitchen_ceiling_2
    state_topic: "zigbee2mqtt/kitchen_ceiling_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    schema: "json"
    command_topic: "zigbee2mqtt/kitchen_ceiling_2/set"

  - platform: mqtt
    name: kitchen_colour_temp
    command_topic: "homeassistant/kitchen"
    color_temp_command_topic: "homeassistant/kitchen/colour_temp"

switch:
  - platform: flux
    name: kitchen_flux
    lights:
      - light.kitchen_colour_temp
    start_time: '15:00'
    stop_time: '22:00'
    start_colortemp: 6500
    sunset_colortemp: 3300
    stop_colortemp: 2000
    transition: 0
    mode: mired
    disable_brightness_adjust: true

binary_sensor:
  - platform: "mqtt"
    name: kitchen_motion_1_occupancy
    state_topic: "zigbee2mqtt/kitchen_motion_1/occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

  - platform: "mqtt"
    name: kitchen_motion_2_occupancy
    state_topic: "zigbee2mqtt/kitchen_motion_2/occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: kitchen_motion_1_illuminance
    state_topic: "zigbee2mqtt/kitchen_motion_1/illuminance"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: kitchen_motion_1_battery
    state_topic: "zigbee2mqtt/kitchen_motion_1/battery"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"

  - platform: "mqtt"
    name: kitchen_motion_2_illuminance
    state_topic: "zigbee2mqtt/kitchen_motion_2/illuminance"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: kitchen_motion_2_battery
    state_topic: "zigbee2mqtt/kitchen_motion_2/battery"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/kitchen_dimmer"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:gesture-double-tap"
    value_template: "{{ value_json.action }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/kitchen_dimmer"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"