sensor:
  - platform: mqtt
    name: pickmypostcode_postcode
    state_topic: "pickmypostcode/userinfo"
    value_template: "{{ value_json.user.data.postcode }}"

  - platform: mqtt
    name: pickmypostcode_main_last_visited
    state_topic: "pickmypostcode/userinfo"
    value_template: "{{ value_json.user.data.mainupdated }}"

  - platform: mqtt
    name: pickmypostcode_survey_last_visited
    state_topic: "pickmypostcode/userinfo"
    value_template: "{{ value_json.user.data.surveyupdated }}"

  - platform: mqtt
    name: pickmypostcode_video_last_visited
    state_topic: "pickmypostcode/userinfo"
    value_template: "{{ value_json.user.data.videoupdated }}"

  - platform: mqtt
    name: pickmypostcode_stackpot_last_visited
    state_topic: "pickmypostcode/userinfo"
    value_template: "{{ value_json.user.data.stackpotupdated }}"

  - platform: mqtt
    name: pickmypostcode_bonus_last_visited
    state_topic: "pickmypostcode/userinfo"
    value_template: "{{ value_json.user.data.bonusupdated }}"

  - platform: mqtt
    name: pickmypostcode_main_last_draw
    state_topic: "pickmypostcode/drawresult/main"
    value_template: "{{ value_json.dateandtime }}"

  - platform: mqtt
    name: pickmypostcode_survey_last_draw
    state_topic: "pickmypostcode/drawresult/survey"
    value_template: "{{ value_json.dateandtime }}"

  - platform: mqtt
    name: pickmypostcode_video_last_draw
    state_topic: "pickmypostcode/drawresult/video"
    value_template: "{{ value_json.dateandtime }}"

  - platform: mqtt
    name: pickmypostcode_stackpot_last_draw
    state_topic: "pickmypostcode/drawresult/stackpot"
    value_template: "{{ value_json.dateandtime }}"

  - platform: mqtt
    name: pickmypostcode_bonus_five_last_draw
    state_topic: "pickmypostcode/drawresult/bonus/five"
    value_template: "{{ value_json.dateandtime }}"

  - platform: mqtt
    name: pickmypostcode_bonus_ten_last_draw
    state_topic: "pickmypostcode/drawresult/bonus/ten"
    value_template: "{{ value_json.dateandtime }}"

  - platform: mqtt
    name: pickmypostcode_bonus_twenty_last_draw
    state_topic: "pickmypostcode/drawresult/bonus/twenty"
    value_template: "{{ value_json.dateandtime }}"

binary_sensor:
  - platform: mqtt
    name: pickmypostcode_main_winner
    state_topic: "pickmypostcode/drawresult/main/winner"
    payload_on: true
    payload_off: false

  - platform: mqtt
    name: pickmypostcode_survey_winner
    state_topic: "pickmypostcode/drawresult/survey/winner"
    payload_on: true
    payload_off: false

  - platform: mqtt
    name: pickmypostcode_video_winner
    state_topic: "pickmypostcode/drawresult/video/winner"
    payload_on: true
    payload_off: false

  - platform: mqtt
    name: pickmypostcode_stackpot_winner
    state_topic: "pickmypostcode/drawresult/stackpot/winner"
    payload_on: true
    payload_off: false

  - platform: mqtt
    name: pickmypostcode_bonus_five_winner
    state_topic: "pickmypostcode/drawresult/bonus/five/winner"
    payload_on: true
    payload_off: false

  - platform: mqtt
    name: pickmypostcode_bonus_ten_winner
    state_topic: "pickmypostcode/drawresult/bonus/ten/winner"
    payload_on: true
    payload_off: false

  - platform: mqtt
    name: pickmypostcode_bonus_twenty_winner
    state_topic: "pickmypostcode/drawresult/bonus/twenty/winner"
    payload_on: true
    payload_off: false

  - platform: mqtt
    name: pickmypostcode_mini_winner
    state_topic: "pickmypostcode/drawresult/mini/winner"
    payload_on: true
    payload_off: false