sensor:
  - platform: mqtt
    name: pickmypostcode_postcode
    state_topic: "pickmypostcode/userinfo"
    value_template: "{{ value_json.user.data.postcode }}"

binary_sensor:
  - platform: mqtt
    name: pickmypostcode_main_winner
    state_topic: "pickmypostcode/drawresult/main/winner"

  - platform: mqtt
    name: pickmypostcode_survey_winner
    state_topic: "pickmypostcode/drawresult/survey/winner"

  - platform: mqtt
    name: pickmypostcode_video_winner
    state_topic: "pickmypostcode/drawresult/video/winner"

  - platform: mqtt
    name: pickmypostcode_stackpot_winner
    state_topic: "pickmypostcode/drawresult/stackpot/winner"

  - platform: mqtt
    name: pickmypostcode_bonus_five_winner
    state_topic: "pickmypostcode/drawresult/bonus/five/winner"

  - platform: mqtt
    name: pickmypostcode_bonus_ten_winner
    state_topic: "pickmypostcode/drawresult/bonus/ten/winner"

  - platform: mqtt
    name: pickmypostcode_bonus_twenty_winner
    state_topic: "pickmypostcode/drawresult/bonus/twenty/winner"

  - platform: mqtt
    name: pickmypostcode_mini_winner
    state_topic: "pickmypostcode/drawresult/mini/winner"