light:
  - platform: mqtt
    name: summer-house_internal
    command_topic: "shellies/summer-house-lights/relay/0/command"
    state_topic: "shellies/summer-house-lights/relay/0"
    payload_on: "on"
    payload_off: "off"
    retain: true
    availability_topic: "shellies/summer-house-lights/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: mqtt
    name: summer-house_flood
    command_topic: "shellies/summer-house-lights/relay/1/command"
    state_topic: "shellies/summer-house-lights/relay/1"
    payload_on: "on"
    payload_off: "off"
    retain: true
    availability_topic: "shellies/summer-house-lights/online"
    payload_available: "true"
    payload_not_available: "false"

binary_sensor:
  - platform: mqtt
    name: summer-house_door
    state_topic: "shellies/summer-house-door/sensor/state"
    payload_on: "open"
    payload_off: "close"
    device_class: "door"
    # availability_topic: "shellies/summer-house-door/online"
    # payload_available: "true"
    # payload_not_available: "false"

sensor:
  - platform: mqtt
    name: summer-house_door_illuminance
    state_topic: "shellies/summer-house-door/sensor/lux"
    unit_of_measurement: "lx"
    device_class: "illuminance"
    # availability_topic: "shellies/summer-house-door/online"
    # payload_available: "true"
    # payload_not_available: "false"

  - platform: mqtt
    name: summer-house_door_battery
    state_topic: "shellies/summer-house-door/sensor/battery"
    unit_of_measurement: "%"
    device_class: "battery"
    # availability_topic: "shellies/summer-house-door/online"
    # payload_available: "true"
    # payload_not_available: "false"

#   - platform: mqtt
#     name: summer-house_internal_light_switch
#     state_topic: "shellies/summer-house-lights/input/0"
#     payload_on: "1"
#     payload_off: "0"
#     availability_topic: "shellies/summer-house-lights/online"
#     payload_available: "true"
#     payload_not_available: "false"

#   - platform: mqtt
#     name: summer-house_flood_light_switch
#     state_topic: "shellies/summer-house-lights/input/1"
#     payload_on: "1"
#     payload_off: "0"
#     availability_topic: "shellies/summer-house-lights/online"
#     payload_available: "true"
#     payload_not_available: "false"