light:
  - platform: mqtt
    name: summer-house_internal
    command_topic: "shellies/summer-house-lights/relay/0/command"
    state_topic: "shellies/summer-house-lights/relay/0"
    payload_on: "on"
    payload_off: "off"
    retain: true
    availability_topic: "shellies/summer-house-lights/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: mqtt
    name: summer-house_flood
    command_topic: "shellies/summer-house-lights/relay/1/command"
    state_topic: "shellies/summer-house-lights/relay/1"
    payload_on: "on"
    payload_off: "off"
    retain: true
    availability_topic: "shellies/summer-house-lights/online"
    payload_available: "true"
    payload_not_available: "false"

binary_sensor:
  - platform: mqtt
    name: summer-house_internal_light_switch
    state_topic: "shellies/summer-house-lights/input/0"
    payload_on: "1"
    payload_off: "0"
    availability_topic: "shellies/summer-house-lights/online"
    payload_available: "true"
    payload_not_available: "false"

  - platform: mqtt
    name: summer-house_flood_light_switch
    state_topic: "shellies/summer-house-lights/input/1"
    payload_on: "1"
    payload_off: "0"
    availability_topic: "shellies/summer-house-lights/online"
    payload_available: "true"
    payload_not_available: "false"