light:
  - platform: "mqtt"
    name: utility
    state_topic: "zigbee2mqtt/utility_group" # zigbee2mqtt group friendlyname: utility_group
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    schema: "json"
    command_topic: "zigbee2mqtt/utility_group/set"

  - platform: "mqtt"
    name: utility_bulb_1
    state_topic: "zigbee2mqtt/utility_bulb_1/ha_state"
    availability_topic: "zigbee2mqtt/utility_bulb_1/availability"
    brightness: true
    schema: "json"
    command_topic: "zigbee2mqtt/utility_bulb_1/set"

  - platform: "mqtt"
    name: utility_bulb_2
    state_topic: "zigbee2mqtt/utility_bulb_2/ha_state"
    availability_topic: "zigbee2mqtt/utility_bulb_2/availability"
    brightness: true
    schema: "json"
    command_topic: "zigbee2mqtt/utility_bulb_2/set"

  - platform: "mqtt"
    name: utility_bulb_3
    state_topic: "zigbee2mqtt/utility_bulb_3/ha_state"
    availability_topic: "zigbee2mqtt/utility_bulb_3/availability"
    brightness: true
    schema: "json"
    command_topic: "zigbee2mqtt/utility_bulb_3/set"

  - platform: "mqtt"
    name: utility_bulb_4
    state_topic: "zigbee2mqtt/utility_bulb_4/ha_state"
    availability_topic: "zigbee2mqtt/utility_bulb_4/availability"
    brightness: true
    schema: "json"
    command_topic: "zigbee2mqtt/utility_bulb_4/set"

  - platform: group
    name: Utility Lights
    entities:
      - light.utility_bulb_1
      - light.utility_bulb_2
      - light.utility_bulb_3
      - light.utility_bulb_4

binary_sensor:
  - platform: "mqtt"
    name: utility_motion_occupancy
    state_topic: "zigbee2mqtt/utility_motion/occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: "true"
    off_delay: 1
    device_class: "motion"

sensor:
  - platform: "mqtt"
    name: utility_motion_illuminance
    state_topic: "zigbee2mqtt/utility_motion/illuminance"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lx"
    device_class: "illuminance"

  - platform: "mqtt"
    name: utility_motion_battery
    state_topic: "zigbee2mqtt/utility_motion/battery"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"